version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    expose:
      - 3000
    environment:
      - APP_PORT=3000
      - APP_NAME=blogFrontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.kitchenservice.rule=Host(`marklund.io`)
    networks:
      - proxy

networks:
  proxy:
    external:
      name: "traefik_proxy"