version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    ports:
      - 3000:80
    networks:
      blog:
       ipv4_address: 10.6.0.2

networks:
  blog:
   name: blog
   ipam:
    driver: default
    config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1