version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.blogFrontend.entrypoints=web
      - traefik.http.routers.blogFrontend.rule=Host(`marklund.io`)
      - traefik.http.services.app-test.loadbalancer.server.port=3000
      - traefik.docker.network=proxy
    networks:
      - proxy
