version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    ports:
      - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.blogFrontend.rule=Host(`marklund.io`)
      - "traefik.http.routers.blogFrontend.entrypoints=websecure"
      - "traefik.http.routers.blogFrontend.tls.certresolver=marklundresolver"
      - traefik.docker.network=proxy
    networks:
      - proxy
networks:
  proxy:
    external:
      name: "traefik_proxy"