version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.kitchenservice.rule=Host(`marklund.io`)